language: ruby
rvm:
- 2.2.2
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
deploy:
  provider: heroku
  api_key:
    secure: WzTTvDoKTzEthmNapW6Jdwp5PmN1Vaenii5MsyU/oqKBB+dkBcC2swWlcgv96WMj+6bk+Dh6GjDhx2gZJUeHUfoGhrfKgm8Nx5z1hknrmMogCu0HcVZV4Y21pQx2Q4vz7Gx6etqeNCSIKFw0SZljVoCBwsgJtfRfD7ga6jBpXSOjTAcDBP2BmCsfiWTjLcZ8BSfIDyr0YJf74ICKqpWCATH3Urs5ynOMcbrMRmepnuv2vjgZz9GONSoU9febrdcAmJV7Rk3mQ+c6Tw3wPSqsTBHBKxzgyUpg2ourhAf80Jhuc1UJEA1tc6J8uEoeIxCO0f+g503wPt9pBQp1GPMT7HBkD12GYx/Fb00nVRvIlM25nXfNQacs0PZtQnJv7Y4zxafm6MDTLsJJBEZ7jx8vB5sO5hDb9f9OVTzWg6oHYd7wZn7BPWvP/jM5t3BkQxhoJA0i00UqQhZkEMNYISEw29F3kPe9YXhVwqoSkVf3T/GHbqDuGPFXIFgpw3oVKWn6P+5Uu4F/q7w47aYGAWn94rskoiM3rrd+YEIr860i0667p5mHsqilr5vez9cMZjVmuKV59KYmIhvXV7IwvSCUOJna3zpnoUz92ko2KwJgrQykERnxNufsb/PPyYqmgXLvf0RZMLHfVejtHayfJ48CK/dOPWE+Y/3NfkBtC3lpMSA=
  app: mighty-journey-90360
  on:
    repo: terra-yucco/rails_enpit
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - rake db:migrate RAILS_ENV=test # いらない？
